name: Publish
run-name: Publish \(${{ github.event_name == 'repository_dispatch' && github.event.client_payload.branch || github.ref_name }}\)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-publish]

permissions:
  id-token: write # Required for OIDC
  contents: write # Potentially needed for creating tags

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dispatch Repository
        uses: actions/checkout@v4
        with:
          ref: refs/heads/${{ github.event_name == 'repository_dispatch' && github.event.client_payload.branch || github.ref_name }}
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --prefer-offline

      - name: Build
        run: pnpm run build

      - name: Publish to NPM
        id: publish
        run: |
          pnpm run release > publish_output.txt 2>&1
          git push --follow-tags
          echo "PUBLISH_OUTPUT<<EOF" >> $GITHUB_ENV
          cat publish_output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          cat publish_output.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # TODO: Notify Slack?
